### ISSUE TITLE
Meteor.methods won't response

### ISSUE THREAD

**Issue by Hongbo-Miao** [dotansimha/angular2-meteor-with-observables#3]
If you call Service function `addProduct` in the Component directly, it is not working now.
```
this.products.addProduct(product);
```
`Meteor.methods` won't response.

```
Meteor.methods({
  addProduct: (product) => {
    console.log('Am I running?'); // here won't run
    return ProductsCollection.insert(product);
  }
})
```
But the ngrx way works well, `Meteor.methods` will response, and add product in the database.
```
this._store.dispatch({
  type: ProductsActions.ADD_PRODUCTS,
  payload: product
});
```

**Comment by dotansimha** [comment]
@Hongbo-Miao that's because you need to run "subscribe" on the return value of the `MeteorObservable.call`, for exmaple:
```
MeteorObservable.call("myMethod").subscribe(...);
```

That's because of the cold observable that triggered only when you subscribe to it's data. 
@Tallyb mentioned that there is a workaround, I am working on it now.

Also, the reason that it works with ngrx, is that ngrx subscribes to the return value when you use `effects`.

**Comment by Hongbo-Miao** [comment]
Yeah, I forget that again. I am still treat `MeteorObservable.call` like `Meteor.call`...

**Comment by dotansimha** [comment]
@Hongbo-Miao and it's ok, I think that the new API should be clear for those who used Meteor.call before. 
The thing with the need to add `subscribe` on the return value is temporary and I will fix it soon!
